name: Deploy Production Application to Server

on:
  push:
    branches: [production]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH Deploy Application
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.PRODUCTION_USER }}
          key: ${{ secrets.PRODUCTION_SSH_KEY }}
          port: ${{ secrets.PRODUCTION_PORT }}
          script: |
            cd ${{ secrets.PRODUCTION_PATH }}
            git fetch origin
            git checkout production
            git pull origin production
            sudo rm -rf node_modules
            sudo rm -rf .next
            sudo nvm use v22.16.0
            sudo npm install --legacy-peer-deps
            sudo npm run build
            sudo npm run pm2:restart || sudo npm run pm2:start
            sudo pm2 save
            sudo pm2 startup
            sudo pm2 status
            
